### ISSUE TITLE
Can't set a min and max values

### ISSUE THREAD

**Issue by smakosh** [cchanxzy/react-currency-input-field#122]
Hi, Great work on the library, love it!

I would love to be able to set a min and max value that can't be crossed, is it currently available? else are you willing to add support to it?

**Comment by cchanxzy** [comment]
Hi, I don't think that is something that this component will be doing because it will be hard to validate correctly.

For example, if you set min value as `10` and the user types `1`, that's already invalid, so do you prevent the user to enter another value? 

I could probably add support so if you step up/down you can't cross the min max, like with the vanilla HTML input.

**Comment by smakosh** [comment]
Yes similar behaviour like with the vanilla HTML

**Comment by cchanxzy** [comment]
Sure, no problem.

I've added option so you can specify min/max and it won't go beyond those values if you are stepping up/down using the arrow keys.

This is in v3.0.2.

Hope that helps :)

**Comment by smakosh** [comment]
Thank you!

**Comment by dcastro-phinx** [comment]
> Sure, no problem.
> 
> I've added option so you can specify min/max and it won't go beyond those values if you are stepping up/down using the arrow keys.
> 
> This is in v3.0.2.
> 
> Hope that helps :)

Hey! where can i find an example about how to set min/max value allowed?

**Comment by cchanxzy** [comment]
@dcastro-phinx please see this example: https://codesandbox.io/s/cool-hill-gvigl?file=/src/App.js
