### ISSUE TITLE
TypeError: r.slice is not a function

### ISSUE THREAD

**Issue by RaddishIoW** [cchanxzy/react-currency-input-field#138]
I'm getting a "TypeError: r.slice is not a function" when trying to format a value using `formatValue`

```
() => {
  const value = jobsArray.sum('fare')
  return formatValue({ value: value, intlConfig: { locale: 'en-GB', currency: 'GBP' } })
}
```
When `value === 0`
I don't think it's an issue with the value?

`jobsArray.sum()` is defined as:
```
sum (key: string): number {
    return this.reduce((a, b) => a + (parseFloat(b[key]) || 0), 0)
  }
```

**Comment by cchanxzy** [comment]
Hi, the `value` passed in should be a `string` rather than a `number` e.g.

```js
formatValue({ value: String(value), intlConfig: { locale: 'en-GB', currency: 'GBP' } })
```

This is because `formatValue` is designed to handle values which might have custom `groupSeparator` or `decimalSeparator`, values that would not always convert into a `number`.

Hope that helps, feel free to re-open this issue if you're still having problems :)

**Comment by RaddishIoW** [comment]
Ah I see - thank you.
Can I open a pull request to change the Readme to make this clearer? The examples don't show the input value as a string.

**Comment by cchanxzy** [comment]
Thanks for PR. Merged now.
