### ISSUE TITLE
Intl.NumberFormat.formatToParts() not supported on iOS <13

### ISSUE THREAD

**Issue by RaddishIoW** [cchanxzy/react-currency-input-field#142]
I'm hitting a problem when trying to use `formatValue` on iOS ~12:
`Intl.NumberFormat.formatToParts()` is not supported...
Is there a way of pollyfilling this?

If not, I'll have to go back to using numbro for formatting display values...

**Comment by cchanxzy** [comment]
Hi, I'm not sure what you mean... iOS 12 is quite broad, do you mean specific browser and version?

https://caniuse.com/mdn-javascript_builtins_intl_numberformat_formattoparts

**Comment by RaddishIoW** [comment]
The specific problem I faced was with an iPad that is running iOS 12.4 - it is not able to be upgraded to anything higher.
According to caniuse.com, nothing earlier than iOS 13 has `Intl.NumberFormat.formatToParts()` support.

I've gone back to using numbro to format currency for display for the time being, but I'm still using react-currency-input-field to provide input support.

**Comment by cchanxzy** [comment]
I see, that is a bit of a disappointment, I apologise for the inconvenience. 

Unfortunately, `Intl.NumberFormat.formatToParts()` is an integral part of the component, so there's not really much I can do unless I rebuild it from the ground up.

I'm surprised you are able to use the input component without encountering the error, because the component uses `formatValue` internally to format the value for display.

**Comment by cchanxzy** [comment]
Going to close this issue now. Feel free to re-open if there are any other problems.
