### ISSUE TITLE
Decimal Separator "." is ignored in Firefox

### ISSUE THREAD

**Issue by thomaskrex** [cchanxzy/react-currency-input-field#144]
In Firefox, the decimal Separator "." is  not emitted by the on valueChanged callback.
When typing "123.", the callback returns "123"

In Chrome this works as expected. I can reproduce this behavior with this sandbox
[Code Sandbox](https://codesandbox.io/s/modest-fermat-1xchd?file=/src/App.js:511-527)

**Comment by cchanxzy** [comment]
Hi, sorry for the late reply.

I just tried the sandbox you've linked, and added `console.log(newValue)` and I can see `123.` being logged. This is in Chrome 89 and Firefox 86.

What version of firefox are you using? and are you using the latest version of this package? (v3.3.0)

**Comment by thomaskrex** [comment]
Hi,
no worries.
I'm using Firefox 86.0.1 on MacOS and react-currency-input-field 3.3.0.
In my case. the console.log statement just logs the value without the dot

**Comment by cchanxzy** [comment]
hmmm, that's certainly weird, I can't seem to reproduce it. This is what I get:

<img width="1101" alt="Screenshot 2021-03-24 at 19 33 31" src="https://user-images.githubusercontent.com/11034578/112372586-e69f7800-8cd7-11eb-8922-2954868c5d72.png">

Also, may I ask why you need the `.` ? because if you're parsing into a number `123.` and `123` are essentially the same?

**Comment by cchanxzy** [comment]
> Also, may I ask why you need the . ? because if you're parsing into a number 123. and 123 are essentially the same?

Sorry, that was a dumb question on my part. Just remembered that the value passed in needs to have a `.` at the end so that user can continue typing the decimal part.

So this is only happening in Firefox for you?
