### ISSUE TITLE
Can't insert decimal separator same as group separator

### ISSUE THREAD

**Issue by Keenic** [cchanxzy/react-currency-input-field#149]
When we have default group separator set as comma (`,`) we can't insert comma as decimal separator. It looks obvious but there is an issue when you have for example UK keyboard on your phone. Since we have `inputmode` set to `decimal` we can't insert any other decimal separator than this comma and in general we can't set any price with decimals in this configuration. 
It might be a general case when we have USD but the user is from UK and can't provide any price and in USA there is comma as thousands separator.
This issue occur on iPhone with English UK, when I had polish language there were `.` and `,` to pick so it was ok but for English UK there is only `,` to pick.

**Comment by cchanxzy** [comment]
Hi, yes that's correct, decimal and group separator cannot be the same because it would be impossible to tell which one was a group separator and which was decimal separator.

I am based in UK, and on my iphone when there is `inputMode="decimal"`, I can see `.` as the decimal separator along with the numbers 0-9.

**Comment by Keenic** [comment]
I can totally understand that it may be impossible to know which separator user entered but the true is that you can't insert `,` as a thousand separator so maybe if user insert `,` or `.` we can treat it as a decimal separator? 
Just tested and your 1st example do not allow me to provide `.` nor `,` on my iOS (I can pick both on decimal keyboard, Polish language) but on macOS I can insert only `.`. 

Another weird thing for me is that you have a `.` as a decimal separator, I've tested 3 phones with UK language and keyboard and all of them had `,`.

**Comment by cchanxzy** [comment]
> Just tested and your 1st example do not allow me to provide `.` nor `,` on my iOS (I can pick both on decimal keyboard, Polish language) but on macOS I can insert only `.`.

Yes, that's correct, the component will only accept numbers or decimal separator. The group separator is added automatically, and user cannot type it.

> Another weird thing for me is that you have a . as a decimal separator, I've tested 3 phones with UK language and keyboard and all of them had ,.

Hmm, that is weird. Because in the UK, `.` is the decimal separator, so it should show up on the num pad by default. At least for all the phones I have used so far.

A possible workaround I can think of is to detect if the user is from the UK or Poland and pass different options to [`intlConfig`](https://www.npmjs.com/package/react-currency-input-field#intl-locale-config). 

e.g.

```js
const intlConfig = isUkUser ? { locale: 'en-US', currency: 'GBP' }  : {...something else}

return (
   <CurrencyInput intlConfig={intlConfig} />;
)
```

Would that work for your case?

**Comment by Keenic** [comment]
> A possible workaround I can think of is to detect if the user is from the UK or Poland and pass different options to intlConfig.

I'm developing an app for US and can't set a GBP as a currency. The case here is that I can't really insert a separator on that weird keyboard. 
And like I mention I can't even insert decimal separator in your 1st example on iOS nor Windows 10.

**Comment by cchanxzy** [comment]
> And like I mention I can't even insert decimal separator in your 1st example on iOS nor Windows 10.

Another solution would to have `inputMode="text` ?  not as elegant but might solve the issue at hand.

Beyond that, I'm not really sure where to go from here because I can't reproduce your issue (not sure if this is locale or keyboard differences), and I don't think being able to type the group separator and interpret it as the decimal separator is a good solution.

Fortunately, this is an open source component, and you can fork it and implement your solution if you think of a good solution!

**Comment by Keenic** [comment]
I'm not sure either if this is a good solution to detect both `,` and `.` as a decimal separator. Like you mention this might be an issue of localization in a browsers. 
I'll not fork this and think about it later when real users will have a problem with this.

I'm closing the issue and maybe it's worth for you to think about interpreting both signs as a decimal separator in the future if more people will have this problem.
