### ISSUE TITLE
alphanumeric can be entered after a period

### ISSUE THREAD

**Issue by SB3933** [cchanxzy/react-currency-input-field#163]
I was trying to use currency input as suggested in Readme file. 

1. I was able to enter chars after a period.
2. When enterying any char after a digit, it considers it to be 0 and count it, you can check on console.log output

**Comment by cchanxzy** [comment]
Hi,

> 1. I was able to enter chars after a period.

Are you saying you're able to enter a non-numeric char after the period? e.g. "1.a"

That doesn't seem to happen for me, please see this [code sandbox](https://codesandbox.io/s/stupefied-euler-cqvn3?file=/src/App.js).

I did notice one bug when testing though, I could enter an abbreviation char after the period ("1.k"), but it would cause a `NaN`. This is fixed in PR #168 .

> 2. When enterying any char after a digit, it considers it to be 0 and count it, you can check on console.log output

Do you mean `onValueChange` is called even if the char entered is not valid. This is true and happens. It's not really a bug though, more of a behaviour. Is this causing you problems?
