### ISSUE TITLE
CurrencyInput doesn't work with formik

### ISSUE THREAD

**Issue by MateuszSm** [cchanxzy/react-currency-input-field#170]
**Describe the bug**
I am trying to integrate `CurrencyInput` fields with formik library in my React app (to omit writing many state setters) and I can't. Every try of inputting something ends with nothing. Using depreciated method is bad idea too. Not sure if this more a feature request or a bug, but I have to ask if there is some elegant workaround or I just shouldn't use your library with formik?

- Input 1) You can't type anything onValueChange is used (probably because it need function which will consume value and name, right?)

- Input 2) You can type something here, because I am using depreciated onChange, but anyway it will throw error.

**To Reproduce**
1. Go to first input from the left (named test1) and try to type some number
2. See console logs
3. Go to first input from the left (named test1) and try to type some number

**Expected behavior**
Integration with formik is possible using `onValueChange` and `onValueChange={formik.handleChange}` or there is some other official way to do this.

**Code Sandbox**
https://codesandbox.io/s/wispy-dust-9hmo9?file=/src/App.jsx

**Additional info**
Library versions in my project:
- "formik": "2.2.7",
- "react": "17.0.1",
- "react-currency-input-field": "3.3.2",
- "typescript": "4.2.3",

**Comment by juliolmuller** [comment]
I think you are going through the same issue of [here](https://github.com/cchanxzy/react-currency-input-field/issues/164) (#64).

Instead of using `handleChange()`, that expects a `ChangeEvent` as param (and therefore know which input is being changed), you should be using `setFieldValue()` where you explicitally tells the input/variable name being changed, and only requires the value to be set itsself.

So your `onValueChange` prop would be something like this:

```tsx
// ...
  <CurrencyInput
    id="test1"
    name="test1"
    value={formik.values.test1}
    onValueChange={(value, name) => {
      formik.setFieldValue(name, value)
    }}
  />
// ...
```

It's a bit more verbose, but works like a charm.

**Comment by MateuszSm** [comment]
Ow, missed that 😮  Thank you, it worked like a charm so I am closing it👌
