### ISSUE TITLE
Add ability to validate field for min value entered

### ISSUE THREAD

**Issue by sweatC** [cchanxzy/react-currency-input-field#177]
**Describe the bug**
It would be great if you add the ability to validate the minimum value for the input. For example, the user can't enter a lower value than 1000. I saw you have an ability to limit max value, but no ability to check for the minimum.

**Expected behavior**
Add prop `minValue` to control a number that can be entered into the field. If `minValue={500}` the user can't enter 400 or what is below 500.

**Comment by cchanxzy** [comment]
Hi, that sort of validation is more of an implementation behaviour rather than component.

There's a `max` and `min` that will prevent user from going beyond those values using the keyboard aroow up/down. 

If you want to prevent user from entering a value you should check it in `onValueChange` function.

Example:

```js
const [value, setValue] = useState(1);

const handleOnValueChange = (value) => {
   if (Number(value) >= 400 && Number(value) <= 500) {
       setValue(value)
   }
}
```
