### ISSUE TITLE
Can't clear the whole input

### ISSUE THREAD

**Issue by moaaz-bhnas** [cchanxzy/react-currency-input-field#36]
I installed the package and used the example in the guide. Everthing is working fine, but when I try to clear the input using `backspace` key, all charaters get deleted, exept for the last one.

```
  <CurrencyInput
    id="input-example"
    name="input-name"
    placeholder="£1,000"
    defaultValue={1000}
    allowDecimals={true}
    decimalsLimit={2}.
    prefix="$"
  />
```

![Screenshot (2)](https://user-images.githubusercontent.com/34780298/81009039-2c4f1a00-8e54-11ea-94e8-09fb724d33e3.png)

**Comment by cchanxzy** [comment]
I noticed you didn't pass a `onChange` function in the component, unlike the example, which I think is causing the issue.

I've added a fix in #38 that will allow it to be optional, because it's not _strictly_ required and works without it, but it is helpful if you need to change className for validation, [see example](https://github.com/cchanxzy/react-currency-input-field/blob/master/src/examples/Example1.tsx#L11:L23).

Your code should now work if you update the package to v0.8.4. Let me know if you have any other comments or suggestions.
