### ISSUE TITLE
Do not allow whitespace at the start of the input value

### ISSUE THREAD

**Issue by alexsthub** [cchanxzy/react-currency-input-field#53]
Hello, I cannot find a way to prevent whitespace at the start of the input.
I've attached a screenshot below. This also happens in the demos that have so graciously been set up. I've added some handling to prevent whitespace but it only works when there are existing numbers in my input value already. Even when the value from the onChange === "", the input will still render those spaces. Can someone help me out with this.
<img width="356" alt="Screen Shot 2020-08-10 at 3 40 55 PM" src="https://user-images.githubusercontent.com/50251447/89838485-3605af00-db20-11ea-96b6-513629f4e0b3.png">

```
onTipValueChange = (value) => {
    if (value !== undefined) value = value.replace(/\s/g, "");
    if (value === undefined || !Number.isNaN(Number(value))) {
      this.setState({ customTip: value });
    }
};
<CurrencyInput
            id="custom-tip"
            name="custom-tip"
            placeholder="$0.00"
            value={this.state.customTip}
            allowDecimals={true}
            decimalsLimit={2}
            maxLength={8}
            prefix={"$"}
            onChange={this.onTipValueChange}
            onBlur={() => {}}
 />
```

**Comment by cchanxzy** [comment]
Hi, I'm not sure I've seen this before, but just to be clear you are referring to the whitespace between the "$" and where you begin to type (in your screenshot).Are you sure there's no css accidentally affecting it?

You mentioned seeing it in the demo too, did you mean here: https://cchanxzy.github.io/react-currency-input-field/ ? Because I don't see the whitespace gap when I view this page.

**Comment by alexsthub** [comment]
Sorry, I think I'm being unclear when I say whitespace. It's not there by default but if you clear the input and then hit the space bar a bunch, you get something like this. Is there a way to prevent the user from using the spacebar? And yes, I am referring to the $ and the point of typing. 
<img width="556" alt="Screen Shot 2020-08-11 at 11 10 23 AM" src="https://user-images.githubusercontent.com/50251447/89933083-63576900-dbc3-11ea-9441-5f4cfac2cc30.png">

**Comment by cchanxzy** [comment]
Ah I see what you mean. In that case I think you should try this:

```js
onTipValueChange = (value) => {
    if (value && !Number.isNaN(value)) {
      this.setState({ customTip: Number(value) });
    }
};
```

or

```js
onTipValueChange = (value) => {
    this.setState({ customTip: Number(value) || 0 });
};
```

Because you want `customTip` to be only a number and not a string. I'm not sure if assignment `if (value !== undefined) value = value.replace(/\s/g, "");` is doing anything. I haven't tested it, but it's generally bad practice to try and manipulate a passed in parameter value.

**Comment by cchanxzy** [comment]
I'm going to close this issue. Feel free to re-open if you're still having problems.
