### ISSUE TITLE
Support for negative dollar amounts

### ISSUE THREAD

**Issue by NickMac573** [cchanxzy/react-currency-input-field#61]
Hi,

Is it possible to add support for negative dollar amounts such as -$20.00 or (20.00) ?

I haven't checked to see how hard it would be to implement but it would be much appreciated

**Comment by cchanxzy** [comment]
Hi, thanks for bringing this up!

I had never tried using it with negative values before, so had no idea it handled it so badly haha.

I've made some changes no tho, so it should handle negative values better. These changes are in the latest release 2.2.0.

Feel free to re-open this issue if you find any bugs due to the changes I made.
