### ISSUE TITLE
clear field after form submission

### ISSUE THREAD

**Issue by miketianchen** [cchanxzy/react-currency-input-field#68]
is there a way to clear the field after the form submission? or a way to control what goes inside the field programmatically?

**Comment by cchanxzy** [comment]
Hi,

This should be possible, but turns out it's not 😅, so thanks for submitting an issue and bringing it to my attention!

I've fixed the issue now, so try the latest version `2.3.1` and it should work as expected.

I've been using [this code sandbox](https://codesandbox.io/s/charming-rain-if7un?file=/src/App.js) for testing, so feel free to use it as an example.

**Comment by miketianchen** [comment]
eyyy thank you! :)
